### ISSUE TITLE
Use process.env for PORT

### ISSUE THREAD

**Issue by erikkrieg** [nestjs/schematics#125]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [ ] Support request

## Current behavior
Starting a new project includes an anti-pattern concerning the handling of configuration. Specifically, `src/main.ts` has the app listen on a hardcoded port.

E.g.
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

On its own this is a seemingly small thing, but it elevates the risk of projects neglecting one of the tenants of _The Twelve-Factor App_:

> Store config in the environment

_https://12factor.net/config_

A consumer of the framework would need to be aware of this anti-pattern and discover [the documentation recommending how to properly handle configuration](https://docs.nestjs.com/techniques/configuration) with Nest.

## Expected behavior

Instead of the app listening to a hardcoded port, use a `ConfigService` class as [suggested in the docs](https://docs.nestjs.com/techniques/configuration) to pull the port from the environment.

Documentation should also link users to the page on configuration techniques.

## Minimal reproduction of the problem with instructions

Start a new project with Nest's CLI (`nest new project`) and see that `src/main.ts` has hardcoded port.

## What is the motivation / use case for changing the behavior?

Two motivations for this feature request:
1. Mitigate risk of applications being built on top of an anti-pattern.
2. Educate developers who are newer to backend development by putting best practices in the critical path of using Nest.

## Environment

<pre><code>
@nestjs/cli: 5.8.0
@nestjs/common: 5.4.0
@nestjs/core: 5.4.0
</code></pre>

**Comment by erikkrieg** [comment]
Yeah, that is a step in the direction I was trying to communicate. Ofc it is up to the maintainers to determine how sophisticated the handling of config in the "basic" project generated from the CLI  should be.

**Comment by Nigelli** [comment]
Hey firstly @kamilmysliwiec, great job on this project; I'm enjoying working with it :).

Using something like `app.listen(process.env.PORT || 3000)` assumes that the env variable is configured and available for this app. Considering this schematic is likely to be used for creating multiple projects we will likely still need to end up changing this. 

I've happened to solve this for our custom schematic that extends this in order to add some business specifics. 

By utilizing environments files(As Angular does) and schema properties in combination, we are able to generate and run multiple nest apps straight from the cli with no additional config. I think something along these lines could provide an elegant solution.

Example:

We set the environment.prod file to expose a server_port property to a environment variable.
`export const environment = {
  production: true,
  server_port: process.env'<%=name%>-port']
};`

And in the dev environment file we used a port chosen at the generate stage.
`export const environment = {
  production: false,
  server_port: '<%=port%>'
};`

The schema.json sets the default and prompts for a choice
`"port": {
      "description": "The dev port this server should run on.",
      "type": "string",
      "default": "3333",
      "x-prompt": "What port would you like to use for the app?"
    },`

In our main.ts we just import `import { environment } from './environments/environment';` and use it like `app.listen(environment.server_port, () => {});`

**Comment by felixhayashi** [comment]
Actually, there is a popular npm package (https://github.com/lorenwest/node-config) that allows you to define config files for different "environments" and at runtime it will pick the config matching `NODE_ENV`. I think this sufficiently abstracts the configuration process and makes it fairly easy to switch environments (see the README examples). As @kamilmysliwiec noted, it is fine that this aspect of the configuration mechanism is not provided as a service since the `bootstrap()` is out of the DI-scope anyways. Of course, nonetheless, nothing prevents you from wrapping the config mechanism in a service to provide it to other parts of your app later.

**Comment by siddrc** [comment]
@felixhayashi yes this works ....thank you so much, especially the fact that node-config has a feature of 
[Custom Env variables ](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables)
It took me a while to realise that I need to keep the `config` folder outside the `src` folder and then it worked beautifully. Thank you

**Comment by Overfacto** [comment]
Using .env is not recommended in production because of security issue. 
Many env variables(like database settings)

**Comment by Overfacto** [comment]
Many people use .env but I have been not saw who think about why we should use .env at first and why there are people that use as `.env.bak`. 
Generally sensitive data should be in soem file and should be not tracked.

Of source, I can understand always setting vars is to be tedious too without encrypted vars patching.
But think about it, if we allow tracking or maintaining env vars on source, 
it can be replaced with other injector (like pm2 ecosystem json), and config service cannot be fixed.

So this feature can be thought so strange. 
Moreover, Nowadays on javascript, pm2 is used on dev / staging env normally.

Maybe you cannot need .env except local env.
Finally I think, it is ok this issue is closed.

**Comment by ryakoviv** [comment]
```
export class AppModule {
   static port: string
  constructor(configService: ConfigService) {
    AppModule.port = configService.get('HTTP_PORT')
  }
}
```

```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(AppModule.port || 3000);
}
bootstrap();
```

**Comment by ahmed-shadab** [comment]
I have gone through official nestjs documentation. Here is what should be done
in main.ts-

import { ConfigService } from '@nestjs/config';

const port = configService.get('PORT');
await app.listen(port|3000);

in .env
PORT=3000

In app.module.ts , import config module if not done ;-)
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
  ]
})
